/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "capiro-blue": {
          50: "#EBF0FF",
          100: "#D6E0FF",
          200: "#ADC1FF",
          300: "#85A3FF",
          400: "#5C84FF",
          500: "#1B4DFF",
          600: "#153DCC",
          700: "#102E99",
          800: "#0A1E66",
          900: "#050F33",
          DEFAULT: "#1B4DFF",
        },
        "signal-blue": {
          50: "#E6F4FF",
          100: "#CCE9FF",
          200: "#99D3FF",
          300: "#66BDFF",
          400: "#33A7FF",
          500: "#0091FF",
          600: "#0074CC",
          700: "#005799",
          800: "#003A66",
          900: "#001D33",
          DEFAULT: "#0091FF",
        },
        "cool-gray": {
          50: "#F8F9FA",
          100: "#F1F3F5",
          200: "#E9ECEF",
          300: "#DEE2E6",
          400: "#CED4DA",
          500: "#ADB5BD",
          600: "#868E96",
          700: "#495057",
          800: "#343A40",
          900: "#212529",
          DEFAULT: "#ADB5BD",
        },
        "soft-white": {
          50: "#FFFFFF",
          100: "#FDFDFE",
          200: "#FAFBFC",
          300: "#F5F7F9",
          400: "#F0F2F5",
          500: "#EBEEF2",
          DEFAULT: "#FAFBFC",
        },
        success: "#12B76A",
        warning: "#F79009",
        error: "#F04438",
        info: "#0091FF",
      },
      fontFamily: {
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "Fira Code",
          "Consolas",
          "Monaco",
          "Courier New",
          "monospace",
        ],
      },
      spacing: {
        sidebar: "16rem",
        "sidebar-collapsed": "4rem",
        nav: "3.5rem",
      },
      maxWidth: {
        content: "80rem",
      },
      borderRadius: {
        card: "0.75rem",
        button: "0.5rem",
        input: "0.5rem",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-in-out",
        "fade-out": "fadeOut 0.2s ease-in-out",
        "slide-in-right": "slideInRight 0.25s ease-out",
        "slide-in-left": "slideInLeft 0.25s ease-out",
        "slide-in-up": "slideInUp 0.2s ease-out",
        "slide-in-down": "slideInDown 0.2s ease-out",
        "scale-in": "scaleIn 0.15s ease-out",
        "spin-slow": "spin 2s linear infinite",
        shimmer: "shimmer 2s linear infinite",
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeOut: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        slideInRight: {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        slideInLeft: {
          from: { transform: "translateX(-100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        slideInUp: {
          from: { transform: "translateY(10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        slideInDown: {
          from: { transform: "translateY(-10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
        scaleIn: {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        shimmer: {
          from: { backgroundPosition: "200% 0" },
          to: { backgroundPosition: "-200% 0" },
        },
      },
    },
  },
  plugins: [],
};
